/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* MENU APP DESIGN */
export const UPDATE_MENU_APP_COLORS_REQUEST = "UPDATE_MENU_APP_COLORS_REQUEST";
export const UPDATE_MENU_APP_SETTINGS_SUCCESS = "UPDATE_MENU_APP_SETTINGS_SUCCESS";
export const UPDATE_MENU_APP_COLORS_FAIL = "UPDATE_MENU_APP_COLORS_FAIL";
export const UPDATE_MENU_APP_LOGO_REQUEST = "UPDATE_MENU_APP_LOGO_REQUEST";
export const UPDATE_MENU_APP_LOGO_FAIL = "UPDATE_MENU_APP_LOGO_FAIL";

/* PRODUCTS */
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_FAIL = "LOAD_PRODUCT_FAIL";
export const TOGGLE_PRODUCT_STATE = "TOGGLE_PRODUCT_STATE";
export const TOGGLE_PRODUCT_STATE_SUCCESS = "TOGGLE_PRODUCT_STATE_SUCCESS";
export const TOGGLE_PRODUCT_STATE_FAIL = "TOGGLE_PRODUCT_STATE_FAIL";
export const CHANGE_PRODUCTS_STATE_SUCCESS = "CHANGE_PRODUCTS_STATE_SUCCESS";
export const CHANGE_PRODUCTS_STATE_FAIL = "CHANGE_PRODUCTS_STATE_FAIL";

/* CATEGORIES */
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
export const LOAD_CATEGORY_FAIL = "LOAD_CATEGORY_FAIL";
export const TOGGLE_CATEGORY_STATE = "TOGGLE_CATEGORY_STATE";
export const TOGGLE_CATEGORY_STATE_SUCCESS = "TOGGLE_CATEGORY_STATE_SUCCESS";
export const TOGGLE_CATEGORY_STATE_FAIL = "TOGGLE_CATEGORY_STATE_FAIL";
export const CHANGE_CATEGORIES_STATE_SUCCESS = "CHANGE_CATEGORIES_STATE_SUCCESS";
export const CHANGE_CATEGORIES_STATE_FAIL = "CHANGE_CATEGORIES_STATE_FAIL";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./my-site/actions";
export * from "./products/actions";
export * from "./categories/actions";